#This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Test Instance
run-name: "[${{ inputs.version }}] MMC instance of ${{ inputs.branch }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
      commit_hash:
        description: 'Hash'
      run_job_url:
        description: 'URL'
      branch:
        description: 'Cleanroom branch'
        default: 'main'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4

    - name: setup python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script # run main.py
      run: python main.py
      env:
        cleanroomDownloadBranch: ${{ inputs.branch || github.event.client_payload.branch }}
        commit_hash: ${{ inputs.commit_hash }}
        run_job_url: ${{ inputs.run_job_url }}
        version: ${{ inputs.version }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Cleanroom_MMC ${{ inputs.version }}
        # A file, directory or wildcard pattern that describes what to upload
        path: build/output
